In [1]:
import pandas as pd
import itertools
import tqdm 
from multiprocessing import Pool 
from defs import *

In [2]:
# Create lists with ranges of SMAs values for combinations calculation
# Short SMA list
windows_sma_short = list(range(2,61))
# Long SMA list
windows_sma_long = list(range(2,61))
# Calculate all of the combinations
sma_combinations = list(itertools.product(windows_sma_short, windows_sma_long))
# Exclude pairs where length do not meat constraints
sma_combinations = [windows for windows in sma_combinations if windows[0] != windows[1]]
sma_combinations = [windows for windows in sma_combinations if windows[0] < windows[1]]

In [3]:
# Simmulate SMA strategy scenarios
if __name__ == '__main__':
   with Pool() as p:
      sma_results_list = list(tqdm.tqdm(p.imap(simmulate_combinations_sma, sma_combinations), total=len(sma_combinations)))
      sma_results_df = pd.DataFrame(sma_results_list)
      
sma_results_df.nlargest(10, 'overall_profit_multiplier')

100%|██████████| 1711/1711 [03:10<00:00,  8.99it/s]

,window_sma_short,window_sma_long,overall_profit_multiplier,average_profit_multiplier,buy_sell_trade_pair_count
8,2,11,5.344419e+12,1.000054,200671.5
11,2,14,3.453257e+12,1.000064,174033.5
9,2,12,3.064482e+12,1.000055,190325.5
5,2,8,2.929454e+12,1.000039,243425.5
10,2,13,2.791900e+12,1.000059,181415.5
12,2,15,1.498478e+12,1.000064,167283.5
7,2,10,9.306806e+11,1.000047,212348.0
13,2,16,6.763289e+11,1.000062,161112.5
4,2,7,4.968988e+11,1.000032,265893.0
3,2,6,4.193811e+11,1.000033,296472.0

In [4]:
# List with possible TRIX window lengths
windows_trix = list(range(2,61))

In [5]:
# Simmulate SMA/TRIX strategy scenarios
if __name__ == '__main__':
   with Pool() as p:
      trix_results_list = list(tqdm.tqdm(p.imap(simmulate_combinations_trix, windows_trix), total=len(windows_trix)))
      trix_results_df = pd.DataFrame(trix_results_list)
      
trix_results_df.nlargest(59, 'average_profit_multiplier')[trix_results_df['average_profit_multiplier'] > 1.001]  # Average profit multiplier higher than commission

100%|██████████| 59/59 [00:16<00:00,  3.62it/s]
/var/folders/m0/r24jzxf914vfqqdvmhxc6t9w0000gn/T/ipykernel_65498/1651898450.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  trix_results_df.nlargest(59, 'average_profit_multiplier')[trix_results_df['average_profit_multiplier'] > 1.001]  # Average profit multiplier higher than commission

,window_sma_short,window_sma_long,window_trix,overall_profit_multiplier,average_profit_multiplier,buy_sell_trade_pair_count
5,2,11,7,1.364477e+36,1.001234,65282.5
4,2,11,6,8.168932e+33,1.001198,63336.0
6,2,11,8,6.527895e+36,1.001190,68444.5
7,2,11,9,3.874160e+37,1.001161,71429.5
8,2,11,10,2.763735e+37,1.001100,74392.5
9,2,11,11,1.760787e+37,1.001055,77039.5
3,2,11,5,2.815247e+31,1.001036,65932.5